name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.io
      IMAGE_API: ${{ secrets.DOCKER_USERNAME }}/k8s-task-manager-api
      IMAGE_WEB: ${{ secrets.DOCKER_USERNAME }}/k8s-task-manager-web

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & push API
      uses: docker/build-push-action@v5
      with:
        context: ./api
        push: true
        tags: ${{ env.IMAGE_API }}:latest

    - name: Build & push Web
      uses: docker/build-push-action@v5
      with:
        context: ./web
        push: true
        tags: ${{ env.IMAGE_WEB }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Deploy con Helm
      run: |
        helm upgrade --install k8s-task-manager ./helm-chart/k8s-task-manager --kubeconfig kubeconfig
